### ISSUE TITLE
Add sample extension skeleton

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave-starter-kit#7]
Add `x/custom` directory with a bunch of placeholder code, that can be used as a starting point. No functionality needed.

* `codec.proto` file that must compile with `make protoc`
* `RegisterRoutes`, `QueryHandler`, `Initializer` endpoints (with no-op implementations)
* One simple msg and state object with the validate logic as just `return x.Metadata.Validate()`

This at least documents the various hooks we need to implement for an app. While the tutorial shows how to build them out

**Comment by orkunkl** [comment]
This issue has been implemented
